@echo off
echo Cleaning output folder...
del output /Q
echo Publishing app project...
start /b /wait "app server" /d scripts publish-app.cmd
echo Publish web project...
start /b /wait "web server" /d scripts publish-web.cmd
echo Running application...
start /b /wait "app" /d output dotnet LandmarkRemark.Api.dll